# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
      
    working_directory: ~/repo

    environment:
      BOOT_AS_ROOT: "yes"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install Boot
          command: sudo bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.boot" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: boot build

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.boot" }}

      # run tests!
      - run: boot bat-test
